import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getRecipeById } from '../services/api';
import { addFavorite, removeFavorite, getFavorites } from '../services/localApi';
import { ArrowLeft, Heart, Loader2, Youtube, List, FileText } from 'lucide-react';

const RecipeDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [recipe, setRecipe] = useState(null);
  const [loading, setLoading] = useState(true);
  const [isFavorite, setIsFavorite] = useState(false);
  const [favoriteId, setFavoriteId] = useState(null); // ID generated by json-server
  const [processing, setProcessing] = useState(false);

  useEffect(() => {
    const fetchDetails = async () => {
      try {
        setLoading(true);
        const data = await getRecipeById(id);
        setRecipe(data);

        // Check if it's already a favorite
        const favorites = await getFavorites();
        const found = favorites.find(fav => fav.idMeal === id);
        if (found) {
          setIsFavorite(true);
          setFavoriteId(found.id);
        }
      } catch (error) {
        console.error("Error loading recipe:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchDetails();
  }, [id]);

  const handleToggleFavorite = async () => {
    if (processing) return;
    setProcessing(true);

    try {
      if (isFavorite) {
        await removeFavorite(favoriteId);
        setIsFavorite(false);
        setFavoriteId(null);
      } else {
        // Save minimal info needed for the card + instructions for offline viewing if we wanted
        const savedRecipe = {
          idMeal: recipe.idMeal,
          strMeal: recipe.strMeal,
          strMealThumb: recipe.strMealThumb,
          strCategory: recipe.strCategory,
          strArea: recipe.strArea,
          strInstructions: recipe.strInstructions,
          strYoutube: recipe.strYoutube,
          // Add a custom note field for the PATCH requirement later
          userNotes: ""
        };
        const newFav = await addFavorite(savedRecipe);
        setFavoriteId(newFav.id);
        setIsFavorite(true);
      }
    } catch (error) {
      console.error("Error toggling favorite:", error);
      alert("Erro ao atualizar favoritos.");
    } finally {
      setProcessing(false);
    }
  };

  if (loading) return (
    <div className="flex justify-center py-20">
      <Loader2 className="animate-spin text-orange-600" size={48} />
    </div>
  );

  if (!recipe) return (
    <div className="text-center py-20 text-gray-500">
      Receita não encontrada.
      <br />
      <button onClick={() => navigate(-1)} className="text-orange-600 hover:underline mt-4">Voltar</button>
    </div>
  );

  // Parse ingredients
  const ingredients = [];
  for (let i = 1; i <= 20; i++) {
    if (recipe[`strIngredient${i}`]) {
      ingredients.push({
        ingredient: recipe[`strIngredient${i}`],
        measure: recipe[`strMeasure${i}`]
      });
    }
  }

  return (
    <div className="max-w-4xl mx-auto">
      <button 
        onClick={() => navigate(-1)} 
        className="flex items-center text-gray-600 hover:text-orange-600 mb-6 transition-colors"
      >
        <ArrowLeft size={20} className="mr-1" />
        Voltar
      </button>

      <div className="bg-white rounded-2xl shadow-lg overflow-hidden border border-gray-100">
        <div className="relative h-80 md:h-96">
          <img 
            src={recipe.strMealThumb} 
            alt={recipe.strMeal} 
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent flex items-end p-8">
            <div className="text-white">
              <h1 className="text-3xl md:text-4xl font-bold mb-2">{recipe.strMeal}</h1>
              <p className="text-lg opacity-90">{recipe.strCategory} • {recipe.strArea}</p>
            </div>
          </div>
        </div>

        <div className="p-8">
          <div className="flex justify-between items-center mb-8 pb-6 border-b border-gray-100">
            <div className="flex space-x-4">
              {recipe.strYoutube && (
                <a 
                  href={recipe.strYoutube} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
                >
                  <Youtube size={20} className="mr-2" />
                  Ver no YouTube
                </a>
              )}
            </div>
            <button
              onClick={handleToggleFavorite}
              disabled={processing}
              className={`flex items-center px-6 py-2 rounded-lg font-semibold transition-all ${
                isFavorite 
                  ? 'bg-red-100 text-red-600 hover:bg-red-200' 
                  : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              <Heart size={20} className={`mr-2 ${isFavorite ? 'fill-current' : ''}`} />
              {isFavorite ? 'Favorito' : 'Adicionar aos Favoritos'}
            </button>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="md:col-span-1">
              <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                <List className="mr-2 text-orange-600" />
                Ingredientes
              </h2>
              <ul className="space-y-2">
                {ingredients.map((item, idx) => (
                  <li key={idx} className="flex justify-between text-gray-700 py-1 border-b border-gray-50 last:border-0">
                    <span className="font-medium">{item.ingredient}</span>
                    <span className="text-gray-500 text-sm">{item.measure}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="md:col-span-2">
              <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                <FileText className="mr-2 text-orange-600" />
                Instruções
              </h2>
              <div className="prose text-gray-700 whitespace-pre-line">
                {recipe.strInstructions}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RecipeDetails;
